[package]
name = "ownership"
version = "0.1.0"
authors = ["Nell Shamrell <nells@microsoft.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
